
import { Category } from './types';

export const AUTHOR_DATA: Record<string, { role: string; bio: string; location: string; image?: string; followers: number; reads: number; instagram?: string; linkedin?: string }> = {
  'Mergior Goriate': {
    role: 'Editor Chefe & Curador Científico',
    bio: 'Apaixonado por desvendar os mistérios do universo e traduzir a complexidade da ciência para todos. Mergior dedica-se a explorar as fronteiras da tecnologia, biologia e cultura pop.',
    location: 'Nampula, Moçambique',
    image: 'https://693d941c8136405902b44b0e.imgix.net/IMG-20250712-WA0014.jpg',
    followers: 3400,
    reads: 12500,
    instagram: 'https://instagram.com/mergior',
    linkedin: 'https://linkedin.com/in/mergior'
  },
  'Sussurros AI (Gemini 2.5)': {
    role: 'Inteligência Artificial Generativa',
    bio: 'Um modelo de linguagem avançado dedicado a auxiliar na pesquisa e redação de conteúdo complexo.',
    location: 'Google Cloud Platform',
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=200&auto=format&fit=crop',
    followers: 8900,
    reads: 45000,
    linkedin: 'https://linkedin.com/company/google-ai'
  }
};

// Use any[] because these objects are augmented with metrics and journalMeta in storageService
export const INITIAL_ARTICLES: any[] = [
  // Artigos Mais Lidos
  {
    id: '1',
    title: 'Computação Quântica: O Futuro da Tecnologia',
    excerpt: 'Descubra como os qubits e a superposição podem revolucionar o processamento de dados e a criptografia mundial.',
    content: '',
    author: 'Mergior Goriate',
    date: '20 Out 2024',
    category: Category.TECHNOLOGY,
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=60&w=800&auto=format&fit=crop',
    readTime: 12,
    status: 'published'
  },
  {
    id: '2',
    title: 'CRISPR e a Engenharia Genética: O Futuro da Medicina Personalizada',
    excerpt: 'Como a edição genética está a abrir portas para a cura de doenças hereditárias e terapias personalizadas.',
    content: '',
    author: 'Mergior Goriate',
    date: '18 Out 2024',
    category: Category.SCIENCE,
    imageUrl: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?q=60&w=800&auto=format&fit=crop',
    readTime: 10,
    status: 'published'
  },
  {
    id: '3',
    title: 'Como Podcasts Estão Transformando o Acesso à Informação e ao Entretenimento',
    excerpt: 'O renascimento do áudio como meio primário de aprendizagem e cultura na era do on-demand.',
    content: '',
    author: 'Mergior Goriate',
    date: '15 Out 2024',
    category: Category.ENTERTAINMENT,
    imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=60&w=800&auto=format&fit=crop',
    readTime: 8,
    status: 'published'
  },
  {
    id: '4',
    title: 'As Últimas Descobertas Científicas: Um Olhar para the Futuro',
    excerpt: 'Uma análise das inovações que marcaram o último trimestre no mundo da ciência aplicada.',
    content: '',
    author: 'Mergior Goriate',
    date: '22 Out 2024',
    category: Category.SCIENCE,
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=60&w=800&auto=format&fit=crop',
    readTime: 9,
    status: 'published'
  },
  {
    id: '5',
    title: 'A Influência da Cultura Pop Asiática: O Crescimento Global do K-pop, Doramas e Anime',
    excerpt: 'Como a onda Hallyu e a animação japonesa conquistaram o ocidente e redefiniram o entretenimento.',
    content: '',
    author: 'Mergior Goriate',
    date: '21 Out 2024',
    category: Category.ENTERTAINMENT,
    imageUrl: 'https://images.unsplash.com/photo-1535189043414-47a3c49a0bed?q=60&w=800&auto=format&fit=crop',
    readTime: 8,
    status: 'published'
  },
  {
    id: '6',
    title: 'Explorando a Neurociência: Um Mergulho na Complexidade do Cérebro',
    excerpt: 'Entenda como biliões de neurónios formam a consciência humana.',
    content: '',
    author: 'Mergior Goriate',
    date: '20 Out 2024',
    category: Category.SCIENCE,
    imageUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?q=60&w=800&auto=format&fit=crop',
    readTime: 10,
    status: 'published'
  },
  {
    id: '7',
    title: 'Os Cinco Padrões de Envelhecimento Cerebral: O que a Ciência nos Revela',
    excerpt: 'Novos estudos apontam para diferentes trajectórias no envelhecimento cognitivo.',
    content: '',
    author: 'Mergior Goriate',
    date: '19 Out 2024',
    category: Category.SCIENCE,
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?q=60&w=800&auto=format&fit=crop',
    readTime: 9,
    status: 'published'
  },
  {
    id: '8',
    title: 'Histórias Curiosas de Invenções Acidentais: Quando o Erro Se Torna Genialidade',
    excerpt: 'Do microondas à penicilina, descubra como o acaso moldou o mundo moderno.',
    content: '',
    author: 'Mergior Goriate',
    date: '18 Out 2024',
    category: Category.CURIOSITIES,
    imageUrl: 'https://images.unsplash.com/photo-1516382799247-87df95d790b7?q=60&w=800&auto=format&fit=crop',
    readTime: 7,
    status: 'published'
  },
  {
    id: '9',
    title: 'Curiosidades sobre o Cérebro Humano: Um Universo Dentro de Nós',
    excerpt: 'Fatos surpreendentes sobre o funcionamento da mente que você provavelmente não sabia.',
    content: '',
    author: 'Mergior Goriate',
    date: '17 Out 2024',
    category: Category.CURIOSITIES,
    imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?q=60&w=800&auto=format&fit=crop',
    readTime: 6,
    status: 'published'
  },
  {
    id: '10',
    title: 'Costumes e Tradições Estranhas ao Redor do Mundo',
    excerpt: 'Uma volta ao mundo através de rituais e hábitos culturais únicos.',
    content: '',
    author: 'Mergior Goriate',
    date: '16 Out 2024',
    category: Category.CURIOSITIES,
    imageUrl: 'https://images.unsplash.com/photo-1528642474498-1af0c17fd8c3?q=60&w=800&auto=format&fit=crop',
    readTime: 7,
    status: 'published'
  },
  {
    id: '11',
    title: 'O Fascinante Mundo dos Sonhos e Pesadelos: Explorando o Inconsciente',
    excerpt: 'Por que sonhamos? A ciência e a psicologia tentam explicar o mundo onírico.',
    content: '',
    author: 'Mergior Goriate',
    date: '15 Out 2024',
    category: Category.CURIOSITIES,
    imageUrl: 'https://images.unsplash.com/photo-1541516160071-4bb0c5af65ba?q=60&w=800&auto=format&fit=crop',
    readTime: 9,
    status: 'published'
  },
  {
    id: '12',
    title: 'A Revolução da Inteligência Artificial Generativa',
    excerpt: 'Como modelos de linguagem como o GPT estão a mudar a forma como trabalhamos e criamos.',
    content: '',
    author: 'Mergior Goriate',
    date: '14 Out 2024',
    category: Category.TECHNOLOGY,
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=60&w=800&auto=format&fit=crop',
    readTime: 10,
    status: 'published'
  },
  {
    id: '13',
    title: 'O Império Romano: Lições de Ascensão e Queda',
    excerpt: 'O que a história de Roma nos pode ensinar sobre a política moderna e a gestão de crises.',
    content: '',
    author: 'Mergior Goriate',
    date: '13 Out 2024',
    category: Category.HISTORY,
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=60&w=800&auto=format&fit=crop',
    readTime: 12,
    status: 'published'
  },
  {
    id: '14',
    title: 'Buracos Negros: Os Monstros do Espaço',
    excerpt: 'Entenda a física por trás dos objetos mais misteriosos e destrutivos do universo.',
    content: '',
    author: 'Mergior Goriate',
    date: '12 Out 2024',
    category: Category.ASTRONOMY,
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=60&w=800&auto=format&fit=crop',
    readTime: 10,
    status: 'published'
  },
  {
    id: '15',
    title: 'A Importância da Saúde Mental no Século XXI',
    excerpt: 'Quebrar o estigma e entender a ansiedade e depressão como questões de saúde pública.',
    content: '',
    author: 'Mergior Goriate',
    date: '11 Out 2024',
    category: Category.HEALTH,
    imageUrl: 'https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=60&w=800&auto=format&fit=crop',
    readTime: 9,
    status: 'published'
  },
  {
    id: '16',
    title: 'Energias Renováveis: O Caminho para a Sustentabilidade',
    excerpt: 'Solar, eólica e hidrogénio verde: as soluções para um futuro livre de carbono.',
    content: '',
    author: 'Mergior Goriate',
    date: '10 Out 2024',
    category: Category.SUSTAINABILITY,
    imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=60&w=800&auto=format&fit=crop',
    readTime: 8,
    status: 'published'
  },
  {
    id: '17',
    title: 'A Psicologia das Cores no Marketing e no Cinema',
    excerpt: 'Como as cores influenciam as nossas emoções e decisões de compra sem percebermos.',
    content: '',
    author: 'Mergior Goriate',
    date: '09 Out 2024',
    category: Category.PSYCHOLOGY,
    imageUrl: 'https://images.unsplash.com/photo-1502691876148-a84978e59af8?q=60&w=800&auto=format&fit=crop',
    readTime: 8,
    status: 'published'
  },
  {
    id: '18',
    title: 'Biohacking: A Ciência de Otimizar o Corpo Humano',
    excerpt: 'Desde jejum intermitente a implantes tecnológicos, até onde podemos ir?',
    content: '',
    author: 'Mergior Goriate',
    date: '08 Out 2024',
    category: Category.BIOLOGY,
    imageUrl: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=60&w=800&auto=format&fit=crop',
    readTime: 9,
    status: 'published'
  },
  {
    id: '19',
    title: 'Big Data: O Ouro Invisível do Século XXI',
    excerpt: 'Como os dados massivos estão a transformar a economia, a privacidade e a tomada de decisão global.',
    content: '',
    author: 'Mergior Goriate',
    date: '25 Out 2024',
    category: Category.BIG_DATA,
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=60&w=800&auto=format&fit=crop',
    readTime: 11,
    status: 'published'
  },
  {
    id: '20',
    title: 'Por que usamos alianças de casamento?',
    excerpt: 'Do antigo Egito à Roma Imperial: a história mística e anatómica por trás do círculo dourado no quarto dedo.',
    content: '',
    author: 'Mergior Goriate',
    date: '28 Out 2024',
    category: Category.CURIOSITIES,
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=60&w=800&auto=format&fit=crop',
    readTime: 5,
    status: 'published'
  },
  {
    id: '21',
    title: 'O que acontece no cérebro minutos antes da morte?',
    excerpt: 'Novos estudos revelam picos de atividade gama que sugerem que a vida realmente pode "passar diante dos olhos".',
    content: '',
    author: 'Mergior Goriate',
    date: '29 Out 2024',
    category: Category.SCIENCE,
    imageUrl: 'https://images.unsplash.com/photo-1530973428-5bf2db2e4d71?q=60&w=800&auto=format&fit=crop',
    readTime: 8,
    status: 'published'
  },
  {
    id: '22',
    title: 'Por que esquecemos sonhos tão rápido?',
    excerpt: 'A neuroquímica explica por que as nossas aventuras noturnas desaparecem segundos após acordarmos.',
    content: '',
    author: 'Mergior Goriate',
    date: '30 Out 2024',
    category: Category.PSYCHOLOGY,
    imageUrl: 'https://images.unsplash.com/photo-1520262454473-a1a82276a574?q=80&w=800&auto=format&fit=crop',
    readTime: 6,
    status: 'published'
  },
  {
    id: '23',
    title: 'O estranho fenômeno do déjà vu explicado',
    excerpt: 'Falha na Matrix ou erro de processamento cerebral? O que a ciência diz sobre a sensação de "já vi isto antes".',
    content: '',
    author: 'Mergior Goriate',
    date: '31 Out 2024',
    category: Category.PSYCHOLOGY,
    imageUrl: 'https://images.unsplash.com/photo-1518644730709-0835105d9daa?q=80&w=800&auto=format&fit=crop',
    readTime: 7,
    status: 'published'
  },
  {
    id: '24',
    title: 'A Matemática do Baralho: 52! Possibilidades',
    excerpt: 'A probabilidade diz que cada vez que embaralha um baralho, cria uma configuração que nunca existiu no universo.',
    content: '',
    author: 'Mergior Goriate',
    date: '01 Nov 2024',
    category: Category.NERD_FACTS,
    imageUrl: 'https://images.unsplash.com/photo-1596205739055-6ee2951722d3?q=60&w=800&auto=format&fit=crop',
    readTime: 6,
    status: 'published'
  },
  {
    id: '25',
    title: 'A origem literal do termo "Bug" na Informática',
    excerpt: 'Como uma traça presa num relé em 1947 mudou o vocabulário tecnológico para sempre.',
    content: '',
    author: 'Mergior Goriate',
    date: '02 Nov 2024',
    category: Category.NERD_FACTS,
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=60&w=800&auto=format&fit=crop',
    readTime: 5,
    status: 'published'
  },
  {
    id: '26',
    title: 'Voyager: O Disco de Ouro enviado aos Extraterrestres',
    excerpt: 'Bach, saudações em 55 línguas e sons de baleias: o que a NASA escolheu para representar a Terra.',
    content: '',
    author: 'Mergior Goriate',
    date: '03 Nov 2024',
    category: Category.NERD_FACTS,
    imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=60&w=800&auto=format&fit=crop',
    readTime: 8,
    status: 'published'
  },
  {
    id: '27',
    title: 'A Engenharia de Precisão de um Bloco LEGO',
    excerpt: 'Por que um bloco de 1958 ainda encaixa perfeitamente num comprado hoje? O segredo está na tolerância zero.',
    content: '',
    author: 'Mergior Goriate',
    date: '04 Nov 2024',
    category: Category.NERD_FACTS,
    imageUrl: 'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?q=60&w=800&auto=format&fit=crop',
    readTime: 5,
    status: 'published'
  },
  {
    id: '28',
    title: 'O Renascimento da Tradição Oral na Era Digital',
    excerpt: 'Como podcasts e audiobooks estão a resgatar a forma mais antiga de contar histórias da humanidade.',
    content: '',
    author: 'Mergior Goriate',
    date: '05 Nov 2024',
    category: Category.CULTURA,
    imageUrl: 'https://images.unsplash.com/photo-1516280440614-6697288d5d38?q=60&w=800&auto=format&fit=crop',
    readTime: 9,
    status: 'published'
  },
  {
    id: '29',
    title: 'Economia Circular: Redesenhar o Futuro sem Desperdício',
    excerpt: 'Mudar do modelo "extrair-produzir-deitar fora" para um sistema regenerativo onde o lixo deixa de existir.',
    content: '',
    author: 'Mergior Goriate',
    date: '06 Nov 2024',
    category: Category.SUSTAINABILITY,
    imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=60&w=800&auto=format&fit=crop',
    readTime: 10,
    status: 'published'
  },
  {
    id: '30',
    title: 'Microbioma: Os Biliões de Habitantes do Seu Corpo',
    excerpt: 'Somos apenas 43% humanos? Descubra como as bactérias intestinais controlam a sua saúde e humor.',
    content: '',
    author: 'Mergior Goriate',
    date: '07 Nov 2024',
    category: Category.BIOLOGY,
    imageUrl: 'https://images.unsplash.com/photo-1631563019676-407b60d89869?q=60&w=800&auto=format&fit=crop',
    readTime: 11,
    status: 'published'
  },
  {
    id: '31',
    title: 'O Papel do Criticismo na Sociedade Actual',
    excerpt: 'Num mundo polarizado, distinguir entre crítica construtiva e cinismo é vital para a evolução intelectual.',
    content: '',
    author: 'Mergior Goriate',
    date: '08 Nov 2024',
    category: Category.CULTURA,
    imageUrl: 'https://images.unsplash.com/photo-1506784365847-bbad939e9335?q=60&w=800&auto=format&fit=crop',
    readTime: 9,
    status: 'published'
  },
  {
    id: '32',
    title: 'O Efeito das Redes Sociais no Pensamento Humano',
    excerpt: 'Dopamina, atenção fragmentada e o impacto dos algoritmos na nossa capacidade de reflexão profunda.',
    content: '',
    author: 'Mergior Goriate',
    date: '09 Nov 2024',
    category: Category.PSYCHOLOGY,
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=60&w=800&auto=format&fit=crop',
    readTime: 10,
    status: 'published'
  },
  {
    id: '33',
    title: 'A Força das Pequenas Decisões na Construção do Nosso Destino',
    excerpt: 'Como o efeito composto e as escolhas diárias moldam o futuro mais do que os grandes eventos.',
    content: '',
    author: 'Mergior Goriate',
    date: '10 Nov 2024',
    category: Category.PSYCHOLOGY,
    imageUrl: 'https://images.unsplash.com/photo-1493612276216-9c59019558f3?q=60&w=800&auto=format&fit=crop',
    readTime: 8,
    status: 'published'
  },
  {
    id: '34',
    title: 'Inteligência Artificial: Aliada ou Ameaça? Uma Análise Objectiva',
    excerpt: 'Para além do hype e do medo: uma visão equilibrada sobre como a IA está a remodelar o mercado de trabalho.',
    content: '',
    author: 'Mergior Goriate',
    date: '11 Nov 2024',
    category: Category.TECHNOLOGY,
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=60&w=800&auto=format&fit=crop',
    readTime: 11,
    status: 'published'
  },
  {
    id: '35',
    title: 'O Futuro da Aprendizagem Online: O Que Podemos Esperar?',
    excerpt: 'Do Zoom à Realidade Virtual: como a tecnologia está a criar salas de aula imersivas e personalizadas.',
    content: '',
    author: 'Mergior Goriate',
    date: '12 Nov 2024',
    category: Category.EDUCATION,
    imageUrl: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?q=60&w=800&auto=format&fit=crop',
    readTime: 9,
    status: 'published'
  },
  {
    id: '36',
    title: 'Criatividade Digital: Quando a Arte Encontra a Tecnologia',
    excerpt: 'NFTs, Arte Generativa e design assistido por IA: as novas fronteiras da expressão artística.',
    content: '',
    author: 'Mergior Goriate',
    date: '13 Nov 2024',
    category: Category.INNOVATION,
    imageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=60&w=800&auto=format&fit=crop',
    readTime: 7,
    status: 'published'
  },
  {
    id: '37',
    title: 'Como as Novas Tecnologias Estão a Redefinir a Educação',
    excerpt: 'Gamificação e tutores de IA: o fim do modelo industrial de ensino e o início da aprendizagem adaptativa.',
    content: '',
    author: 'Mergior Goriate',
    date: '14 Nov 2024',
    category: Category.EDUCATION,
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=60&w=800&auto=format&fit=crop',
    readTime: 10,
    status: 'published'
  },
  {
    id: '38',
    title: 'Do Sonho ao Projecto: Como Transformar Ideias em Realidade',
    excerpt: 'Estratégias práticas de gestão e inovação para tirar os seus planos do papel e construir o futuro.',
    content: '',
    author: 'Mergior Goriate',
    date: '15 Nov 2024',
    category: Category.INNOVATION,
    imageUrl: 'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?q=60&w=800&auto=format&fit=crop',
    readTime: 9,
    status: 'published'
  }
];
