# Generated by Django 5.0.14 on 2026-02-13 20:48

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(help_text='Resumo curto do artigo', max_length=500, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo (Markdown)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/%Y/%m/', verbose_name='Imagem de Capa')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em Revisão'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('published_at', models.DateTimeField(blank=True, help_text='Deixe em branco para publicar imediatamente', null=True, verbose_name='Data de Publicação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('reading_time', models.IntegerField(default=0, help_text='Calculado automaticamente', verbose_name='Tempo de Leitura (min)')),
                ('views', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('meta_title', models.CharField(blank=True, help_text='Título para SEO (máx. 60 caracteres)', max_length=60, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, help_text='Descrição para SEO (máx. 160 caracteres)', max_length=160, verbose_name='Meta Descrição')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL Canônica')),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100, verbose_name='DOI')),
                ('citations', models.IntegerField(default=0, verbose_name='Citações')),
                ('altmetric_score', models.IntegerField(default=0, verbose_name='Altmetric Score')),
                ('download_count', models.IntegerField(default=0, verbose_name='Downloads')),
                ('issn', models.CharField(default='2024-99XX', max_length=50, verbose_name='ISSN')),
                ('volume', models.IntegerField(default=1, verbose_name='Volume')),
                ('issue', models.IntegerField(default=1, verbose_name='Edição')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nome do Autor')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email do Autor')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article', verbose_name='Artigo')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('content', models.TextField(verbose_name='Conteúdo da Sugestão')),
                ('type', models.CharField(choices=[('correction', 'Correção'), ('addition', 'Adição'), ('clarification', 'Esclarecimento')], max_length=20, verbose_name='Tipo')),
                ('reference_text', models.TextField(blank=True, help_text='Trecho do artigo ao qual a sugestão se refere', verbose_name='Texto de Referência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footnotes', to='articles.article', verbose_name='Artigo')),
            ],
            options={
                'verbose_name': 'Sugestão',
                'verbose_name_plural': 'Sugestões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='articles_ar_publish_c1a2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='articles_ar_status_edb746_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='articles_ar_slug_452037_idx'),
        ),
    ]
