# Generated by Django 5.0.14 on 2026-02-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='summary',
            new_name='excerpt',
        ),
    ]
