# Generated by Django 5.0.14 on 2026-02-17 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_summary_article_excerpt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/', verbose_name='Foto de Perfil')),
                ('bio', models.TextField(blank=True, help_text='Breve descrição do percurso académico (máx. 500 caracteres)', max_length=500, verbose_name='Mini Biografia Académica')),
                ('institution', models.CharField(blank=True, max_length=100, verbose_name='Instituição')),
                ('scientific_area', models.CharField(blank=True, max_length=100, verbose_name='Área Científica')),
                ('citation_count', models.IntegerField(default=0, verbose_name='Nº de Citações')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('research_gate_url', models.URLField(blank=True, verbose_name='ResearchGate')),
                ('orcid_url', models.URLField(blank=True, verbose_name='ORCID')),
                ('external_publications', models.TextField(blank=True, help_text='Listar DOI ou títulos de publicações externas importantes', verbose_name='Publicações Relevantes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Perfil de Investigador',
                'verbose_name_plural': 'Perfis de Investigadores',
            },
        ),
    ]
