# Generated by Django 5.0.14 on 2026-02-17 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Remetente')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do Remetente')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Autor Destinatário')),
            ],
            options={
                'verbose_name': 'Mensagem para Autor',
                'verbose_name_plural': 'Mensagens para Autores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_email', models.EmailField(max_length=254, verbose_name='Email do Seguidor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Seguindo desde')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Autor Seguido')),
                ('follower_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following_authors', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador Seguidor (Opcional)')),
            ],
            options={
                'verbose_name': 'Seguidor',
                'verbose_name_plural': 'Seguidores',
                'ordering': ['-created_at'],
                'unique_together': {('author', 'follower_email')},
            },
        ),
    ]
