# Generated by Django 5.0.14 on 2026-02-17 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_authormessage_authorfollower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50, verbose_name='Campo Alvo')),
                ('suggestion_text', models.TextField(verbose_name='Texto Sugerido')),
                ('rationale', models.TextField(blank=True, verbose_name='Justificação da IA')),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='articles.article')),
            ],
            options={
                'verbose_name': 'Sugestão de IA',
                'verbose_name_plural': 'Sugestões de IA',
            },
        ),
        migrations.CreateModel(
            name='ArticleChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo do Chunk')),
                ('token_count', models.IntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, help_text='Vetor de embedding (fallback para SQLite)', null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='articles.article')),
            ],
            options={
                'verbose_name': 'Chunk de Artigo',
                'verbose_name_plural': 'Chunks de Artigos',
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('view', 'Visualização'), ('like', 'Like'), ('read_finish', 'Leitura Completa'), ('search', 'Pesquisa')], max_length=20)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('read_time_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='articles.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Utilizador',
                'verbose_name_plural': 'Eventos de Utilizadores',
            },
        ),
    ]
