# Generated by Django 5.0.14 on 2026-02-18 00:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_aisuggestion_articlechunk_userevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(verbose_name='Dados do Evento')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Ocorrido em')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
            ],
            options={
                'verbose_name': 'Evento Outbox',
                'verbose_name_plural': 'Eventos Outbox',
                'ordering': ['occurred_at'],
            },
        ),
    ]
