# Generated by Django 5.0.14 on 2026-02-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_outboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.JSONField(blank=True, default=list, help_text="Ex: [{'type': 'verified', 'label': 'Autor Verificado'}, {'type': 'top', 'label': 'Top Investigador'}]", verbose_name='Distintivos/Badges'),
        ),
    ]
