# Generated by Django 5.0.14 on 2026-02-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_profile_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='karma',
            field=models.IntegerField(default=0, help_text='Pontos acumulados por contribuições aprovadas', verbose_name='Reconhecimento (Karma)'),
        ),
    ]
