# Generated by Django 5.0.14 on 2026-02-18 01:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_profile_karma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200)),
                ('excerpt', models.TextField(help_text='Resumo curto do artigo', max_length=500, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo (Markdown)')),
                ('cover_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagem de Capa')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em Revisão'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Estado')),
                ('published_at', models.DateTimeField(blank=True, help_text='Deixe em branco para publicar imediatamente', null=True, verbose_name='Data de Publicação')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('reading_time', models.IntegerField(default=0, help_text='Calculado automaticamente', verbose_name='Tempo de Leitura (min)')),
                ('views', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('meta_title', models.CharField(blank=True, help_text='Título para SEO (máx. 60 caracteres)', max_length=60, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, help_text='Descrição para SEO (máx. 160 caracteres)', max_length=160, verbose_name='Meta Descrição')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL Canônica')),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100, verbose_name='DOI')),
                ('citations', models.IntegerField(default=0, verbose_name='Citações')),
                ('altmetric_score', models.IntegerField(default=0, verbose_name='Altmetric Score')),
                ('download_count', models.IntegerField(default=0, verbose_name='Downloads')),
                ('issn', models.CharField(default='2024-99XX', max_length=50, verbose_name='ISSN')),
                ('volume', models.IntegerField(default=1, verbose_name='Volume')),
                ('issue', models.IntegerField(default=1, verbose_name='Edição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='articles.category', verbose_name='Categoria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Artigo',
                'verbose_name_plural': 'historical Artigos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceite'), ('declined', 'Recusada'), ('completed', 'Concluída')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, verbose_name='Comentários ao Autor')),
                ('editor_notes', models.TextField(blank=True, verbose_name='Notas Privadas ao Editor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='articles.article')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Revisão',
                'verbose_name_plural': 'Pedidos de Revisão',
            },
        ),
    ]
