# Generated by Django 6.0.2 on 2026-02-20 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0012_userlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('uniques', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='articles.article')),
            ],
            options={
                'verbose_name': 'Métrica Diária',
                'verbose_name_plural': 'Métricas Diárias',
                'indexes': [models.Index(fields=['day', '-views'], name='analytics_a_day_b72021_idx')],
                'unique_together': {('article', 'day')},
            },
        ),
        migrations.CreateModel(
            name='ArticleMetricMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(db_index=True, max_length=7)),
                ('views', models.PositiveIntegerField(default=0)),
                ('uniques', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_metrics', to='articles.article')),
            ],
            options={
                'verbose_name': 'Métrica Mensal',
                'verbose_name_plural': 'Métricas Mensais',
                'indexes': [models.Index(fields=['year_month', '-views'], name='analytics_a_year_mo_161477_idx')],
                'unique_together': {('article', 'year_month')},
            },
        ),
        migrations.CreateModel(
            name='ArticleMetricWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_week', models.CharField(db_index=True, max_length=10)),
                ('views', models.PositiveIntegerField(default=0)),
                ('uniques', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_metrics', to='articles.article')),
            ],
            options={
                'verbose_name': 'Métrica Semanal',
                'verbose_name_plural': 'Métricas Semanais',
                'indexes': [models.Index(fields=['year_week', '-views'], name='analytics_a_year_we_f5e4c1_idx')],
                'unique_together': {('article', 'year_week')},
            },
        ),
    ]
